// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: sharptown.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImageProcessor_Transform_FullMethodName = "/sharptown.v1.ImageProcessor/Transform"
)

// ImageProcessorClient is the client API for ImageProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Image processing service backed by sharp. Mirrors packages/server-grpc/proto.
type ImageProcessorClient interface {
	Transform(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TransformRequest, TransformResponse], error)
}

type imageProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewImageProcessorClient(cc grpc.ClientConnInterface) ImageProcessorClient {
	return &imageProcessorClient{cc}
}

func (c *imageProcessorClient) Transform(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TransformRequest, TransformResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ImageProcessor_ServiceDesc.Streams[0], ImageProcessor_Transform_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TransformRequest, TransformResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ImageProcessor_TransformClient = grpc.BidiStreamingClient[TransformRequest, TransformResponse]

// ImageProcessorServer is the server API for ImageProcessor service.
// All implementations must embed UnimplementedImageProcessorServer
// for forward compatibility.
//
// Image processing service backed by sharp. Mirrors packages/server-grpc/proto.
type ImageProcessorServer interface {
	Transform(grpc.BidiStreamingServer[TransformRequest, TransformResponse]) error
	mustEmbedUnimplementedImageProcessorServer()
}

// UnimplementedImageProcessorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImageProcessorServer struct{}

func (UnimplementedImageProcessorServer) Transform(grpc.BidiStreamingServer[TransformRequest, TransformResponse]) error {
	return status.Error(codes.Unimplemented, "method Transform not implemented")
}
func (UnimplementedImageProcessorServer) mustEmbedUnimplementedImageProcessorServer() {}
func (UnimplementedImageProcessorServer) testEmbeddedByValue()                        {}

// UnsafeImageProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageProcessorServer will
// result in compilation errors.
type UnsafeImageProcessorServer interface {
	mustEmbedUnimplementedImageProcessorServer()
}

func RegisterImageProcessorServer(s grpc.ServiceRegistrar, srv ImageProcessorServer) {
	// If the following call panics, it indicates UnimplementedImageProcessorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImageProcessor_ServiceDesc, srv)
}

func _ImageProcessor_Transform_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ImageProcessorServer).Transform(&grpc.GenericServerStream[TransformRequest, TransformResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ImageProcessor_TransformServer = grpc.BidiStreamingServer[TransformRequest, TransformResponse]

// ImageProcessor_ServiceDesc is the grpc.ServiceDesc for ImageProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sharptown.v1.ImageProcessor",
	HandlerType: (*ImageProcessorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Transform",
			Handler:       _ImageProcessor_Transform_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "sharptown.proto",
}
