// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: sharptown.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransformOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         *uint32                `protobuf:"varint,1,opt,name=width,proto3,oneof" json:"width,omitempty"`
	Height        *uint32                `protobuf:"varint,2,opt,name=height,proto3,oneof" json:"height,omitempty"`
	Rotate        *int32                 `protobuf:"varint,3,opt,name=rotate,proto3,oneof" json:"rotate,omitempty"`
	Flip          bool                   `protobuf:"varint,4,opt,name=flip,proto3" json:"flip,omitempty"`
	Blur          *uint32                `protobuf:"varint,5,opt,name=blur,proto3,oneof" json:"blur,omitempty"`
	TintR         *uint32                `protobuf:"varint,6,opt,name=tint_r,json=tintR,proto3,oneof" json:"tint_r,omitempty"`
	TintG         *uint32                `protobuf:"varint,7,opt,name=tint_g,json=tintG,proto3,oneof" json:"tint_g,omitempty"`
	TintB         *uint32                `protobuf:"varint,8,opt,name=tint_b,json=tintB,proto3,oneof" json:"tint_b,omitempty"`
	Grayscale     bool                   `protobuf:"varint,9,opt,name=grayscale,proto3" json:"grayscale,omitempty"`
	RemoveAlpha   bool                   `protobuf:"varint,10,opt,name=remove_alpha,json=removeAlpha,proto3" json:"remove_alpha,omitempty"`
	EnsureAlpha   bool                   `protobuf:"varint,11,opt,name=ensure_alpha,json=ensureAlpha,proto3" json:"ensure_alpha,omitempty"`
	ConvertTo     string                 `protobuf:"bytes,12,opt,name=convert_to,json=convertTo,proto3" json:"convert_to,omitempty"`
	Crop          string                 `protobuf:"bytes,13,opt,name=crop,proto3" json:"crop,omitempty"`
	CropOffset    string                 `protobuf:"bytes,14,opt,name=crop_offset,json=cropOffset,proto3" json:"crop_offset,omitempty"`
	SmartCrop     bool                   `protobuf:"varint,15,opt,name=smart_crop,json=smartCrop,proto3" json:"smart_crop,omitempty"`
	Fit           string                 `protobuf:"bytes,16,opt,name=fit,proto3" json:"fit,omitempty"`
	Background    string                 `protobuf:"bytes,17,opt,name=background,proto3" json:"background,omitempty"`
	AutoOrient    bool                   `protobuf:"varint,18,opt,name=auto_orient,json=autoOrient,proto3" json:"auto_orient,omitempty"`
	Dpr           *float64               `protobuf:"fixed64,19,opt,name=dpr,proto3,oneof" json:"dpr,omitempty"`
	AspectRatio   *float64               `protobuf:"fixed64,20,opt,name=aspect_ratio,json=aspectRatio,proto3,oneof" json:"aspect_ratio,omitempty"`
	Brightness    *float64               `protobuf:"fixed64,21,opt,name=brightness,proto3,oneof" json:"brightness,omitempty"`
	Contrast      *float64               `protobuf:"fixed64,22,opt,name=contrast,proto3,oneof" json:"contrast,omitempty"`
	Saturation    *float64               `protobuf:"fixed64,23,opt,name=saturation,proto3,oneof" json:"saturation,omitempty"`
	Exposure      *float64               `protobuf:"fixed64,24,opt,name=exposure,proto3,oneof" json:"exposure,omitempty"`
	Hue           *float64               `protobuf:"fixed64,25,opt,name=hue,proto3,oneof" json:"hue,omitempty"`
	Gamma         *float64               `protobuf:"fixed64,26,opt,name=gamma,proto3,oneof" json:"gamma,omitempty"`
	Colorize      string                 `protobuf:"bytes,27,opt,name=colorize,proto3" json:"colorize,omitempty"`
	Sepia         *float64               `protobuf:"fixed64,28,opt,name=sepia,proto3,oneof" json:"sepia,omitempty"`
	Invert        bool                   `protobuf:"varint,29,opt,name=invert,proto3" json:"invert,omitempty"`
	Threshold     *uint32                `protobuf:"varint,30,opt,name=threshold,proto3,oneof" json:"threshold,omitempty"`
	Sharpen       *float64               `protobuf:"fixed64,31,opt,name=sharpen,proto3,oneof" json:"sharpen,omitempty"`
	OilPaint      *uint32                `protobuf:"varint,32,opt,name=oil_paint,json=oilPaint,proto3,oneof" json:"oil_paint,omitempty"`
	Quality       *uint32                `protobuf:"varint,33,opt,name=quality,proto3,oneof" json:"quality,omitempty"`
	Progressive   bool                   `protobuf:"varint,34,opt,name=progressive,proto3" json:"progressive,omitempty"`
	StripMetadata *bool                  `protobuf:"varint,35,opt,name=strip_metadata,json=stripMetadata,proto3,oneof" json:"strip_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformOptions) Reset() {
	*x = TransformOptions{}
	mi := &file_sharptown_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformOptions) ProtoMessage() {}

func (x *TransformOptions) ProtoReflect() protoreflect.Message {
	mi := &file_sharptown_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformOptions.ProtoReflect.Descriptor instead.
func (*TransformOptions) Descriptor() ([]byte, []int) {
	return file_sharptown_proto_rawDescGZIP(), []int{0}
}

func (x *TransformOptions) GetWidth() uint32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *TransformOptions) GetHeight() uint32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *TransformOptions) GetRotate() int32 {
	if x != nil && x.Rotate != nil {
		return *x.Rotate
	}
	return 0
}

func (x *TransformOptions) GetFlip() bool {
	if x != nil {
		return x.Flip
	}
	return false
}

func (x *TransformOptions) GetBlur() uint32 {
	if x != nil && x.Blur != nil {
		return *x.Blur
	}
	return 0
}

func (x *TransformOptions) GetTintR() uint32 {
	if x != nil && x.TintR != nil {
		return *x.TintR
	}
	return 0
}

func (x *TransformOptions) GetTintG() uint32 {
	if x != nil && x.TintG != nil {
		return *x.TintG
	}
	return 0
}

func (x *TransformOptions) GetTintB() uint32 {
	if x != nil && x.TintB != nil {
		return *x.TintB
	}
	return 0
}

func (x *TransformOptions) GetGrayscale() bool {
	if x != nil {
		return x.Grayscale
	}
	return false
}

func (x *TransformOptions) GetRemoveAlpha() bool {
	if x != nil {
		return x.RemoveAlpha
	}
	return false
}

func (x *TransformOptions) GetEnsureAlpha() bool {
	if x != nil {
		return x.EnsureAlpha
	}
	return false
}

func (x *TransformOptions) GetConvertTo() string {
	if x != nil {
		return x.ConvertTo
	}
	return ""
}

func (x *TransformOptions) GetCrop() string {
	if x != nil {
		return x.Crop
	}
	return ""
}

func (x *TransformOptions) GetCropOffset() string {
	if x != nil {
		return x.CropOffset
	}
	return ""
}

func (x *TransformOptions) GetSmartCrop() bool {
	if x != nil {
		return x.SmartCrop
	}
	return false
}

func (x *TransformOptions) GetFit() string {
	if x != nil {
		return x.Fit
	}
	return ""
}

func (x *TransformOptions) GetBackground() string {
	if x != nil {
		return x.Background
	}
	return ""
}

func (x *TransformOptions) GetAutoOrient() bool {
	if x != nil {
		return x.AutoOrient
	}
	return false
}

func (x *TransformOptions) GetDpr() float64 {
	if x != nil && x.Dpr != nil {
		return *x.Dpr
	}
	return 0
}

func (x *TransformOptions) GetAspectRatio() float64 {
	if x != nil && x.AspectRatio != nil {
		return *x.AspectRatio
	}
	return 0
}

func (x *TransformOptions) GetBrightness() float64 {
	if x != nil && x.Brightness != nil {
		return *x.Brightness
	}
	return 0
}

func (x *TransformOptions) GetContrast() float64 {
	if x != nil && x.Contrast != nil {
		return *x.Contrast
	}
	return 0
}

func (x *TransformOptions) GetSaturation() float64 {
	if x != nil && x.Saturation != nil {
		return *x.Saturation
	}
	return 0
}

func (x *TransformOptions) GetExposure() float64 {
	if x != nil && x.Exposure != nil {
		return *x.Exposure
	}
	return 0
}

func (x *TransformOptions) GetHue() float64 {
	if x != nil && x.Hue != nil {
		return *x.Hue
	}
	return 0
}

func (x *TransformOptions) GetGamma() float64 {
	if x != nil && x.Gamma != nil {
		return *x.Gamma
	}
	return 0
}

func (x *TransformOptions) GetColorize() string {
	if x != nil {
		return x.Colorize
	}
	return ""
}

func (x *TransformOptions) GetSepia() float64 {
	if x != nil && x.Sepia != nil {
		return *x.Sepia
	}
	return 0
}

func (x *TransformOptions) GetInvert() bool {
	if x != nil {
		return x.Invert
	}
	return false
}

func (x *TransformOptions) GetThreshold() uint32 {
	if x != nil && x.Threshold != nil {
		return *x.Threshold
	}
	return 0
}

func (x *TransformOptions) GetSharpen() float64 {
	if x != nil && x.Sharpen != nil {
		return *x.Sharpen
	}
	return 0
}

func (x *TransformOptions) GetOilPaint() uint32 {
	if x != nil && x.OilPaint != nil {
		return *x.OilPaint
	}
	return 0
}

func (x *TransformOptions) GetQuality() uint32 {
	if x != nil && x.Quality != nil {
		return *x.Quality
	}
	return 0
}

func (x *TransformOptions) GetProgressive() bool {
	if x != nil {
		return x.Progressive
	}
	return false
}

func (x *TransformOptions) GetStripMetadata() bool {
	if x != nil && x.StripMetadata != nil {
		return *x.StripMetadata
	}
	return false
}

type TransformRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TransformRequest_Options
	//	*TransformRequest_Chunk
	Payload       isTransformRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformRequest) Reset() {
	*x = TransformRequest{}
	mi := &file_sharptown_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformRequest) ProtoMessage() {}

func (x *TransformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharptown_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformRequest.ProtoReflect.Descriptor instead.
func (*TransformRequest) Descriptor() ([]byte, []int) {
	return file_sharptown_proto_rawDescGZIP(), []int{1}
}

func (x *TransformRequest) GetPayload() isTransformRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TransformRequest) GetOptions() *TransformOptions {
	if x != nil {
		if x, ok := x.Payload.(*TransformRequest_Options); ok {
			return x.Options
		}
	}
	return nil
}

func (x *TransformRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*TransformRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isTransformRequest_Payload interface {
	isTransformRequest_Payload()
}

type TransformRequest_Options struct {
	Options *TransformOptions `protobuf:"bytes,1,opt,name=options,proto3,oneof"`
}

type TransformRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*TransformRequest_Options) isTransformRequest_Payload() {}

func (*TransformRequest_Chunk) isTransformRequest_Payload() {}

type TransformResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformResponse) Reset() {
	*x = TransformResponse{}
	mi := &file_sharptown_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformResponse) ProtoMessage() {}

func (x *TransformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sharptown_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformResponse.ProtoReflect.Descriptor instead.
func (*TransformResponse) Descriptor() ([]byte, []int) {
	return file_sharptown_proto_rawDescGZIP(), []int{2}
}

func (x *TransformResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_sharptown_proto protoreflect.FileDescriptor

const file_sharptown_proto_rawDesc = "" +
	"\n" +
	"\x0fsharptown.proto\x12\fsharptown.v1\"\xad\n" +
	"\n" +
	"\x10TransformOptions\x12\x19\n" +
	"\x05width\x18\x01 \x01(\rH\x00R\x05width\x88\x01\x01\x12\x1b\n" +
	"\x06height\x18\x02 \x01(\rH\x01R\x06height\x88\x01\x01\x12\x1b\n" +
	"\x06rotate\x18\x03 \x01(\x05H\x02R\x06rotate\x88\x01\x01\x12\x12\n" +
	"\x04flip\x18\x04 \x01(\bR\x04flip\x12\x17\n" +
	"\x04blur\x18\x05 \x01(\rH\x03R\x04blur\x88\x01\x01\x12\x1a\n" +
	"\x06tint_r\x18\x06 \x01(\rH\x04R\x05tintR\x88\x01\x01\x12\x1a\n" +
	"\x06tint_g\x18\a \x01(\rH\x05R\x05tintG\x88\x01\x01\x12\x1a\n" +
	"\x06tint_b\x18\b \x01(\rH\x06R\x05tintB\x88\x01\x01\x12\x1c\n" +
	"\tgrayscale\x18\t \x01(\bR\tgrayscale\x12!\n" +
	"\fremove_alpha\x18\n" +
	" \x01(\bR\vremoveAlpha\x12!\n" +
	"\fensure_alpha\x18\v \x01(\bR\vensureAlpha\x12\x1d\n" +
	"\n" +
	"convert_to\x18\f \x01(\tR\tconvertTo\x12\x12\n" +
	"\x04crop\x18\r \x01(\tR\x04crop\x12\x1f\n" +
	"\vcrop_offset\x18\x0e \x01(\tR\n" +
	"cropOffset\x12\x1d\n" +
	"\n" +
	"smart_crop\x18\x0f \x01(\bR\tsmartCrop\x12\x10\n" +
	"\x03fit\x18\x10 \x01(\tR\x03fit\x12\x1e\n" +
	"\n" +
	"background\x18\x11 \x01(\tR\n" +
	"background\x12\x1f\n" +
	"\vauto_orient\x18\x12 \x01(\bR\n" +
	"autoOrient\x12\x15\n" +
	"\x03dpr\x18\x13 \x01(\x01H\aR\x03dpr\x88\x01\x01\x12&\n" +
	"\faspect_ratio\x18\x14 \x01(\x01H\bR\vaspectRatio\x88\x01\x01\x12#\n" +
	"\n" +
	"brightness\x18\x15 \x01(\x01H\tR\n" +
	"brightness\x88\x01\x01\x12\x1f\n" +
	"\bcontrast\x18\x16 \x01(\x01H\n" +
	"R\bcontrast\x88\x01\x01\x12#\n" +
	"\n" +
	"saturation\x18\x17 \x01(\x01H\vR\n" +
	"saturation\x88\x01\x01\x12\x1f\n" +
	"\bexposure\x18\x18 \x01(\x01H\fR\bexposure\x88\x01\x01\x12\x15\n" +
	"\x03hue\x18\x19 \x01(\x01H\rR\x03hue\x88\x01\x01\x12\x19\n" +
	"\x05gamma\x18\x1a \x01(\x01H\x0eR\x05gamma\x88\x01\x01\x12\x1a\n" +
	"\bcolorize\x18\x1b \x01(\tR\bcolorize\x12\x19\n" +
	"\x05sepia\x18\x1c \x01(\x01H\x0fR\x05sepia\x88\x01\x01\x12\x16\n" +
	"\x06invert\x18\x1d \x01(\bR\x06invert\x12!\n" +
	"\tthreshold\x18\x1e \x01(\rH\x10R\tthreshold\x88\x01\x01\x12\x1d\n" +
	"\asharpen\x18\x1f \x01(\x01H\x11R\asharpen\x88\x01\x01\x12 \n" +
	"\toil_paint\x18  \x01(\rH\x12R\boilPaint\x88\x01\x01\x12\x1d\n" +
	"\aquality\x18! \x01(\rH\x13R\aquality\x88\x01\x01\x12 \n" +
	"\vprogressive\x18\" \x01(\bR\vprogressive\x12*\n" +
	"\x0estrip_metadata\x18# \x01(\bH\x14R\rstripMetadata\x88\x01\x01B\b\n" +
	"\x06_widthB\t\n" +
	"\a_heightB\t\n" +
	"\a_rotateB\a\n" +
	"\x05_blurB\t\n" +
	"\a_tint_rB\t\n" +
	"\a_tint_gB\t\n" +
	"\a_tint_bB\x06\n" +
	"\x04_dprB\x0f\n" +
	"\r_aspect_ratioB\r\n" +
	"\v_brightnessB\v\n" +
	"\t_contrastB\r\n" +
	"\v_saturationB\v\n" +
	"\t_exposureB\x06\n" +
	"\x04_hueB\b\n" +
	"\x06_gammaB\b\n" +
	"\x06_sepiaB\f\n" +
	"\n" +
	"_thresholdB\n" +
	"\n" +
	"\b_sharpenB\f\n" +
	"\n" +
	"_oil_paintB\n" +
	"\n" +
	"\b_qualityB\x11\n" +
	"\x0f_strip_metadata\"q\n" +
	"\x10TransformRequest\x12:\n" +
	"\aoptions\x18\x01 \x01(\v2\x1e.sharptown.v1.TransformOptionsH\x00R\aoptions\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\t\n" +
	"\apayload\")\n" +
	"\x11TransformResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk2b\n" +
	"\x0eImageProcessor\x12P\n" +
	"\tTransform\x12\x1e.sharptown.v1.TransformRequest\x1a\x1f.sharptown.v1.TransformResponse(\x010\x01B7Z5github.com/e1berd/sharptown/clients/go/internal/pb;pbb\x06proto3"

var (
	file_sharptown_proto_rawDescOnce sync.Once
	file_sharptown_proto_rawDescData []byte
)

func file_sharptown_proto_rawDescGZIP() []byte {
	file_sharptown_proto_rawDescOnce.Do(func() {
		file_sharptown_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sharptown_proto_rawDesc), len(file_sharptown_proto_rawDesc)))
	})
	return file_sharptown_proto_rawDescData
}

var file_sharptown_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sharptown_proto_goTypes = []any{
	(*TransformOptions)(nil),  // 0: sharptown.v1.TransformOptions
	(*TransformRequest)(nil),  // 1: sharptown.v1.TransformRequest
	(*TransformResponse)(nil), // 2: sharptown.v1.TransformResponse
}
var file_sharptown_proto_depIdxs = []int32{
	0, // 0: sharptown.v1.TransformRequest.options:type_name -> sharptown.v1.TransformOptions
	1, // 1: sharptown.v1.ImageProcessor.Transform:input_type -> sharptown.v1.TransformRequest
	2, // 2: sharptown.v1.ImageProcessor.Transform:output_type -> sharptown.v1.TransformResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sharptown_proto_init() }
func file_sharptown_proto_init() {
	if File_sharptown_proto != nil {
		return
	}
	file_sharptown_proto_msgTypes[0].OneofWrappers = []any{}
	file_sharptown_proto_msgTypes[1].OneofWrappers = []any{
		(*TransformRequest_Options)(nil),
		(*TransformRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sharptown_proto_rawDesc), len(file_sharptown_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sharptown_proto_goTypes,
		DependencyIndexes: file_sharptown_proto_depIdxs,
		MessageInfos:      file_sharptown_proto_msgTypes,
	}.Build()
	File_sharptown_proto = out.File
	file_sharptown_proto_goTypes = nil
	file_sharptown_proto_depIdxs = nil
}
